#!/usr/bin/env bash
#databank-bin-scripts/svc_hooks/boot

###
### boot - service hook for booting up databank; called by
###        /etc/init.d/databank
###

# Load environment variables
. $HOME/.bashrc

source $HOME/bin/scripts/env.sh

# Start Rails
$HOME/bin/scripts/start-rails
