#!/usr/bin/env bash
#databank-bin-scripts/start-rails

source $HOME/bin/scripts/env.sh

# Clear Rails cache
( cd $DATABANK_HOME ; RAILS_ENV=$RAILS_ENV bundle exec rails databank:rails_cache:clear )

# Start Delayed Job
( cd $DATABANK_HOME ; RAILS_ENV=$RAILS_ENV bin/delayed_job -n 10 start)

# Start Passenger
( cd $DATABANK_HOME ; RAILS_ENV=$RAILS_ENV bundle install ; RAILS_ENV=$RAILS_ENV bundle exec passenger start -d -e $RAILS_ENV --nginx-config-template nginx.conf.erb --max-pool-size 20 )

echo "Started Illinois Data Bank"
